<? header("refresh: 30; url=http://www.profiwh.cz") ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
<head>
    <title>Tato doména je hostována u ProfiWH - webhosting na profesionální úrovni</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="keywords" content="webhosting, registrace domén, domény, .eu, hosting, maily" />
    <meta name="description" content="Doména je hostována u ProfiWH - hosting na profesionální úrovni" />
    <meta http-equiv="Author" content="ProfiWH - WinSoft Company s.r.o." />
    <base href="http://web11.profiwh.com/" />
    <link href="css/screen.css" media="screen" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript" src="js/external.js"></script>
</head>
<body>

<div id="root">

<a href="http://www.profiwh.cz"
title="ProfiWH - webhosting na profesionální úrovni"><img src="images/logo.png"
alt="Profiwh - webhosting" /></a><br />

<h1>Tato doména je hostována u ProfiWH</h1>

<h3>This domain name is hosted by ProfiWH</h3>

<div id="footer">
<strong>ProfiWH</strong> -

<a href="http://www.profiwh.cz/" rel="external"
title="ProfiWH - levný profesionální hosting, serverhosting, housing, provizní systém pro obchodní partnery">webhosting</a>,
<a href="http://www.profiwh.cz/cenik-domen.html" rel="external"
title="Registrace domény .cz, .eu, generických domén .com, .net, .biz, .info a mnoho dalších atraktivních tld">registrace domén</a>,
<a href="http://www.eu-domeny-registrace.cz" rel="external"
title="Akreditovaný registrátor .eu domén, registrace, správa, změna registrátora">akreditovaný registrátor domény .eu</a>
</div>

</div>

</body>
</html>
